# golangci-lint configuration for k8s-eni-tagger
run:
  timeout: 5m
  tests: true
  skip-dirs:
    - bin
    - vendor
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Go static analysis
    - typecheck     # Type check Go code
    - unused        # Check for unused code
    - gofmt         # Check formatting
    - goimports     # Check import formatting
    - misspell      # Check for misspelled words
    - revive        # Fast, configurable, extensible, flexible, and beautiful linter
    - gosec         # Security checker
    - gocritic      # Opinionated Go source code linter
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Find unused function parameters

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    check-shadowing: true
  
  revive:
    rules:
      - name: exported
        disabled: false
      - name: var-naming
        disabled: false
  
  gosec:
    excludes:
      - G404  # Allow math/rand (not used for crypto)

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    # Exclude test files from certain checks
    - path: _test\.go
      linters:
        - gosec
        - errcheck
